In [7]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
y=[1,23,4]
print(y)
print(type(y))

[1, 23, 4]
<class 'list'>


## %timeit 
- will how much time take to execute the array or list
## %%timeit
- wil show us how much time take to execute the whole program

In [10]:
%timeit [j**4 for j in range(2,20)]

5.74 µs ± 1.8 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
# array
import numpy as np
%timeit np.arange(2,20)**4

3.4 µs ± 1.06 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Numpy Array

In [21]:
import numpy as np
x=['apple','banana','mango','orange']
y=np.array([x])
print(y)
# ndim is used to check the dimension of the array
print(y.ndim)

[['apple' 'banana' 'mango' 'orange']]
2


In [19]:
# user input list or array
l=[]
for i in range(1,5):
    int_1=int(input("enter:"))
    l.append(int_1)
    
print(np.array(l))  
print(l)

enter:12
enter:13
enter:24
enter:24
[12 13 24 24]
[12, 13, 24, 24]


In [25]:
# creating 2 dimension array
ar2=np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [28]:
ar3=np.array([[[1,2,3,4],[1,2,3,5],[20,30,40,100]]])
print(ar3)
print(ar3.ndim)

[[[  1   2   3   4]
  [  1   2   3   5]
  [ 20  30  40 100]]]
3


In [33]:
# for creating n dimension array use (ndmin=n numbers)
arn=np.array([1,2,3,4,5],ndmin=6)
print(arn)
print(arn.ndim)

[[[[[[1 2 3 4 5]]]]]]
6


# Spacial Numpy Array