In [5]:
import numpy as np

In [6]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)
print(arr)

[1 2 3 4 5]


In [5]:
type(arr)
# shape funciton helps us to see how many number of row and column in the array
arr.shape

(5,)

In [7]:
#converting List in array
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[5,7,9,15,19]
arr=np.array([my_list1,my_list2, my_list3])
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 5,  7,  9, 15, 19]])

In [10]:
arr.shape

(3, 5)

In [8]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  5,  7],
       [ 9, 15, 19]])

In [12]:
arr.shape

(3, 5)

In [7]:
import numpy as np
my_array=[1,2,3,4,5]
type(my_array)
arr=np.array(my_array)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [8]:
arr.shape

(5,)

In [12]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [9]:
array1=[1,2,3,4]
array2=[5,6,7,8]
array3=[9,10,11,12]
arr=np.array([array1,array2,array3])
for count in array3:
    print(count)

9
10
11
12


In [18]:
arr.shape

(3, 4)

In [19]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [23]:
arr.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [24]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
 arr[1:2,1: ]

array([[6, 7, 8]])

In [2]:
sumit="Sumit"
print(sumit)

Sumit


In [1]:
print("Sumit")

Sumit


In [2]:
print('Hello world!')

Hello world!
