## Arithmetic Operation in array

In [2]:
import numpy as np

In [2]:
#Add
var=np.array([1,2,3,4])
varadd=var+3
print(varadd)

[4 5 6 7]


In [4]:
# Addition of two array
var1=np.array([1,2, 3 ,4])
var2=np.array([2,3,4,9])
varadd=var1+var2
print(varadd)

[ 3  5  7 13]


In [6]:
var=np.array([1,2,3,4])
varsub=var-3
print(varsub)

[-2 -1  0  1]


In [7]:
# subtraction of Two array
var1=np.array([1,2, 3 ,4])
var2=np.array([2,3,4,9])
varsub=var1-var2
print(varsub)

[-1 -1 -1 -5]


In [10]:
var1=np.array([1,2, 3 ,4])
var2=np.array([2,3,4,9])
varmulti=var1*var2
print(varmulti)

[ 2  6 12 36]


In [9]:
var1=np.array([1,2, 3 ,4])
var2=np.array([2,3,4,9])
varsub=var1/var2
print(varsub)

[0.5        0.66666667 0.75       0.44444444]


In [3]:
var1=np.array([1,2, 3 ,4])
var2=np.array([2,3,4,9])
varsub=var1%var2
print(varsub)

[1 2 3 4]


In [9]:
var1=np.array([1,2, 3 ,4])
var2=np.array([2,3,4,9])
a=[1,2,3,4]
b=[2,4,6,8]
vardd=np.add(a,b)
varsub=np.subtract(a,b)
varmulti=np.multiply(a,b)
varsub=np.subtract(a,b)
print(varadd)
print(varsub)
print(varmulti)

[ 3  5  7 13]
[-1 -2 -3 -4]
[ 2  8 18 32]


# 2d array


In [11]:
var2d=np.array([[1,2,3,4],[2,3,4,5]])
var21=np.array([[1,3,8,4],[2,3,6,5]])
varadd=np.multiply(var2d,var21)
print(varadd)

[[ 1  6 24 16]
 [ 4  9 24 25]]


In [12]:
# reciprocal 2d array perform

var=[10,20,30,40]
varresi=np.reciprocal(var)
print(varresi)


[0 0 0 0]


### Arithmetic Functions

In [30]:
# Min vs max 
var=np.array([3,6,7,8,5,10,15,20,2,9,1])
varmin=np.min(var)
varmax=np.max(var)

print("max:",varmax,np.argmin(var))
print()
print("min:",varmin,np.argmax(var))
print
print("sqrt: ", np.sqrt(var))

max: 20 10

min: 1 7
sqrt:  [1.73205081 2.44948974 2.64575131 2.82842712 2.23606798 3.16227766
 3.87298335 4.47213595 1.41421356 3.         1.        ]


In [27]:
# 2d array
var1=np.array([[2,4,6,8,10],[1,3,5,7,9]])
print(np.max(var1,axis=1))


[10  9]


In [32]:
# Value of Sin cos
var3=[1,2,3,4]
print(np.sin(var3))

print(np.cos(var3))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [35]:
# cumlity Sum
var3=[1,2,3,4]
print(np.cumsum(var3))

[ 1  3  6 10]
