In [1]:
import numpy as np


In [2]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)
print(arr)

[1 2 3 4 5]


In [3]:
my_Demo=['Sumit',100,100.50]
arr=np.array(my_Demo)
print(arr)
type(arr)
arr.shape

['Sumit' '100' '100.5']


(3,)

In [4]:
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[5,6,7,8,9]
arr=np.array([list1,list2,list3])

In [5]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [5, 6, 7, 8, 9]])

In [6]:
arr.shape

(3, 5)

In [7]:
arr.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [5, 6, 7, 8, 9]])

In [8]:
arr[0:2,:2]

array([[1, 2],
       [2, 3]])

In [9]:
arr[1:,1:]

array([[3, 4, 5, 6],
       [6, 7, 8, 9]])

In [10]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 5, 6],
       [7, 8, 9]])

In [11]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [5, 6, 7, 8, 9]])

In [14]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [20]:
rr=np.arange(0,10,step=2)

In [21]:
rr

array([0, 2, 4, 6, 8])

In [22]:
np.linspace(5,15,30)

array([ 5.        ,  5.34482759,  5.68965517,  6.03448276,  6.37931034,
        6.72413793,  7.06896552,  7.4137931 ,  7.75862069,  8.10344828,
        8.44827586,  8.79310345,  9.13793103,  9.48275862,  9.82758621,
       10.17241379, 10.51724138, 10.86206897, 11.20689655, 11.55172414,
       11.89655172, 12.24137931, 12.5862069 , 12.93103448, 13.27586207,
       13.62068966, 13.96551724, 14.31034483, 14.65517241, 15.        ])

In [32]:
## copy function and broadcasting 
aarr=[1,2,4,5,6]
aarr[3:]=100


TypeError: can only assign an iterable

In [30]:
aarr

[1, 2, 4]