
### Special types of Numpy

In [2]:
# Zeros

import numpy as np

arrayZero=np.zeros(4)
print(arrayZero)
print()

arzero=np.zeros((3,4))
print(arzero)


[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# Array filled with Ones

arOne=np.ones(6)
print(arOne)
print()
arone=np.ones((5,5))
print(arone)

[1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
# Array fill with empty
ar_em=np.empty(4)
print(ar_em)

[0. 0. 0. 0.]


In [10]:
# Array fill in range

ar_range=np.arange(4)
print(ar_range)
print()

ar_range1=np.arange(6)
print(ar_range1)

[0 1 2 3]

[0 1 2 3 4 5]


In [11]:
# Array with diagonal element

ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# ar_dia=np.eye(5,5)
print(ar_dia)

# linspace

In [14]:
ar_lin=np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


# Numpy arrays with random numbers

## Rand function

In [2]:
import numpy as np

In [19]:
var=np.random.rand(5)
print(var)

[0.66036809 0.81128447 0.53484433 0.02231771 0.68083438]


In [20]:
var1=np.random.rand(2,5)
print(var1)

[[0.23605365 0.90185205 0.24515462 0.13591757 0.40212536]
 [0.3545534  0.92292477 0.48358288 0.57467362 0.31972894]]


## randn()
- the funciton is used to generate a random value close to zero.
- This may return postive or negative numbers as well,

## ranf()

- the function for doing random smapling in numpy .
- it returns an array of specified shape and fills it with 
- random floats in the half open interval

# randn()

In [21]:
var2=np.random.randn(10)
print(var2)

[-2.34693634 -0.71932166  0.47273607 -1.37771338 -0.40961353  0.81842575
  1.13037783 -1.04004298 -0.94106074  0.96053217]


# ranf()

In [23]:
var3=np.random.ranf(12)
print(var3)

[0.35286976 0.33962264 0.27945821 0.09204222 0.73605175 0.49428432
 0.92537895 0.9549659  0.20402249 0.47766906 0.15845388 0.69840912]


## Randint()
- this function is used to generate a random number from given range

In [27]:
var4=np.random.randint(5,10,15) # min,max,total numbers
print(var4)

[9 7 8 7 9 6 7 5 9 9 5 6 5 8 5]


In [ ]:
## Data Type of numpy arrays

In [3]:
var=np.array([1,2,3,4])
print("Data Type: ",var.dtype)

Data Type:  int32


In [4]:
var=np.array([1.0,2.5,3,4])
print("Data Type: ",var.dtype)

Data Type:  float64


In [5]:
letters=np.array(['A','b','c','d'])
print("Data Type: ",letters.dtype)

Data Type:  <U1


In [6]:
mixed=np.array(['A','b','c','d',1,2,3,4])
print("Data Type: ",mixed.dtype)

Data Type:  <U11


## Data types as function
- i- integer
- b- boolean
- u- unsigned integer
- f- float
- c- complex float
- m- timedelta
- M- datetime
- O- object
- S- string
- U- unicode string

In [10]:
x=np.array([1,2,3,4],dtype=np.int8)

print("Data Type: ",x.dtype)
print(x)

Data Type:  int8
[1 2 3 4]


In [11]:
x1=np.array([1,2,3,4],dtype="f")

print("Data Type: ",x1.dtype)
print(x1)

Data Type:  float32
[1. 2. 3. 4.]


In [15]:
x2=np.array([1,2,3,4])
new=np.float32(x2)
print(x2)
print(new)
print("Data Type: ",new.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
Data Type:  float32


In [16]:
new1=x2.astype(float)
print(new1)

[1. 2. 3. 4.]
